apiVersion: enterprise.splunk.com/v1alpha1
kind: SplunkEnterprise
metadata:
  name: withdfs
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  enableDFS: true
  splunkVolumes:
  - name: licenses
    configMap:
      name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
  topology:
    indexers: 3
    searchHeads: 3
    sparkWorkers: 3