apiVersion: enterprise.splunk.com/v1alpha1
kind: SplunkEnterprise
metadata:
  name: example-splunkenterprise
spec:
  config:
    splunkPassword: helloworld456
    splunkStartArgs: --accept-license
    splunkLicense:
      volumeSource:
        configMap:
          name: dfs-license
      licensePath: /dfs-license.lic
  topology:
    indexers: 3
    searchHeads: 3