apiVersion: enterprise.splunk.com/v1alpha1
kind: SplunkEnterprise
metadata:
  name: example-splunkenterprise
spec:
  config:
    splunkPassword: helloworld456
    splunkStartArgs: --accept-license
    defaultsConfigMapName: splunk-defaults
  standalones: 1