apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  appRepo:
    appsRepoPollIntervalSeconds: 60
    defaults:
      volumeName: volume_app_repo
      scope: local
    appSources:
      - name: s1Apps
        location: standalone
    volumes:
      - name: volume_app_repo
        storageType: s3
        region: us-west-2
        provider: aws
        path: testapps
        endpoint: https://cmpoperatorteam.blob.core.windows.net
